name: DevOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t vannsak237/devops-web:latest .

      - name: Push Docker image
        run: docker push vannsak237/devops-web:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop devops-container || true
            docker rm devops-container || true
            docker pull vannsak237/devops-web:latest
            docker run -d -p 80:80 --name devops-container vannsak237/devops-web:latest
